### ISSUE TITLE
dark theme?

### ISSUE THREAD

**Issue by heathsnow** [jsanz/gh-pages-minima-starter#7]
I'm trying to use the minima [skins](https://github.com/jekyll/minima#skins) configuration:

```yaml
minima:
  skin: dark
```

but it's not taking....any ideas?

**Comment by jsanz** [comment]
That feature is unfortunately not yet released as the last [stable release](https://github.com/jekyll/minima/releases) is 2.5.1.

You can check anytime your installed version with `bundle info minima` and as soon as 3.0 comes out, you should be able to run `bundle upgrade minima` to get access to the last features, even maybe some tweaks to adapt to a major version will be needed.

There's this related issue, if you want to learn more jekyll/minima#584

**Comment by heathsnow** [comment]
Thanks for the quick response @jsanz .....I'll just deal with the blinding white light for now :)

**Comment by jsanz** [comment]
Just a reminder that you can override minima styles editing the [`assets/main.scss`](https://github.com/jsanz/gh-pages-minima-starter/blob/master/assets/main.scss) file to easily change colors for fonts, backgrounds, margins, etc.
