### ISSUE TITLE
How to add a right navigation panel?

### ISSUE THREAD

**Issue by snambi** [jsanz/gh-pages-minima-starter#9]
Thanks for the wonderful tutorials. 
The tutorial contains almost everything I am looking for.

I am looking for the following to organize the content better,

1. `_posts` folder should have a hierarchical directory structure to store the posts.
2. Have a left or right navigation panel that follows the same directory structure in `_posts`

**Comment by jsanz** [comment]
Hi @snambi thanks for your kind words. Regarding your questions:

1. `_posts` folder is not that flexible on the structure, take a look at the [jekyll file structure docs](https://jekyllrb.com/docs/structure/)
2. Unfortunately that's not included in the minima theme. There is [this hack](https://github.com/jwrr/minima-sidebar) repo that adds a table of contents in the sidebar but I have never used it.

Hope this helps, closing the issue but feel free to reopen if you have further feedback regarding this topic.
